### ISSUE TITLE
Issues with cJSON

### ISSUE THREAD

**Issue by lumidify** [stephenjsweeney/tbftss#18]
When trying to compile with GCC 6.1.1, I'm getting errors such as this one:
```
src/json/cJSON.c: In function ‘cJSON_strcasecmp’:
src/json/cJSON.c:41:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  if (!s1) return (s1==s2)?0:1;if (!s2) return 1;
  ^~
```
and notes such as this:
```
src/json/cJSON.c:41:31: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  if (!s1) return (s1==s2)?0:1;if (!s2) return 1;
                               ^~
```
All of these can be fixed by going through and putting the second statement on a new line. Is anyone else experiencing this?

**Comment by stephenjsweeney** [comment]
On GCC 4 here, so not seen them. The "misleading-indentation" error is new in GCC 6. There are several options to fixing this:

1. Remove -Werror so they only come out as warnings.
2. Use a GCC compile switch to ignore the warning completely. I think -Wno-misleading-indentation would work here.
3. Move all the affected if statements to a second line.

The latter would be best. Given there are a lot of them, a search and replace might suffice, though it will mess up the code indentation a bit. Can do:

sed -i 's/;if/;\nif/g' src/json/cJSON.c

and

sed -i 's/; if/;\nif/g' src/json/cJSON.c

to update these. Don't know if it will work 100%, though.

**Comment by lumidify** [comment]
I actually managed to get it to work by only moving ~4 statements, but it would probably be best to just move all of them.

**Comment by stephenjsweeney** [comment]
I've pushed an update to develop. Should work okay, fingers crossed, but you should give compiling a go and seeing what happens (GCC 6 not in Mint 13's repo).

**Comment by lumidify** [comment]
Yup, it works now.
